apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java
          image: 558607277863.dkr.ecr.us-east-1.amazonaws.com/java-app:latest
          ports:
            - name: java-port
              containerPort: 8080
