apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: java-app
  type: LoadBalancer
  ports:
    - name: java
      port: 80
      targetPort: 8080
      protocol: TCP